enum SimErrors {
    OUT_OF_INSTRUCTIONS =  "OUT OF INSTRUCTIONS",
    CANNOT_GRAB_SECOND_FILE = "CANNOT GRAB A SECOND FILE",
    NO_FILE_IS_HELD = "NO FILE IS HELD",
    TOO_MANY_CYCLES = "TOO MANY CYCLES",
}
