enum SimErrors {
    CANNOT_READ_PAST_END_OF_FILE = "CANNOT READ PAST END OF FILE",
    GENERAL_ERROR = "GENERAL ERROR", // this is not part of the official guidelines
    OUT_OF_INSTRUCTIONS = "OUT OF INSTRUCTIONS",
    CANNOT_GRAB_SECOND_FILE = "CANNOT GRAB A SECOND FILE",
    NO_FILE_IS_HELD = "NO FILE IS HELD",
    TOO_MANY_CYCLES = "TOO MANY CYCLES",
    LINK_ID_NOT_FOUND = "LINK ID NOT FOUND",
    EXA_KILLED = "EXA_KILLED",
}

export default SimErrors;
